FROM --platform=arm64 node:20 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM --platform=arm64 nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

ENV PORT=80
EXPOSE $PORT
CMD ["nginx", "-g", "daemon off;"]