name: CI Pipeline for ASP.NET API Application using Dockerhub

on:
  push:
    branches: ["sp-006-frontend-ui"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["sp-006-frontend-ui"]

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        id: vars
        run: |
          echo "GITHUB_REF is: $GITHUB_REF"
           tag=${GITHUB_REF#refs/*/}
           tag=${tag%% *}
           echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Setup Git Config
        run: |
          git config user.name "Stephen Phyo"
          git config user.email "stephenphyo2019.official@gmail.com"

      - name: Save Version
        id: version
        run: echo ::set-output name=tag

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKERHUB_USERNAME }}
          password: ${{  secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push to Docker Hub Repository
        run: |
          docker build -t ${{  secrets.DOCKERHUB_USERNAME }}/sp-006-phoenix-talk-frontend:${{ steps.vars.outputs.tag }} -f Dockerfile.prod .
          docker push ${{  secrets.DOCKERHUB_USERNAME }}/sp-006-phoenix-talk-frontend:${{ steps.vars.outputs.tag }}
